### ISSUE TITLE
早期vue源码运行不起来

### ISSUE THREAD

**Issue by youngwind** [zhenyong/notebook#1]
hi，最近我想通过逐commit的方式来研究vue的源码，找到了你的这篇文章。但是我却没有办法运行起来早期的vue代码，情况如下。
我checkout到的commit id是这个：30f67ab14090900a28c18db01cf631c037d36e81，
也就是[这个页面](https://github.com/vuejs/vue/commits/dev?page=57)的第一行。按照作者的contributing.md中的开发步骤，安装好各种东西之后编译生成dist/vue.js。调用方式和执行结果参考下图。
![2016-08-17 5 12 56](https://cloud.githubusercontent.com/assets/8401872/17730956/b6b6b50c-649d-11e6-9a2b-50dac9d8cbd8.png)
**为什么页面上还显示{{message}}呢？**
是不是早期的vue就没有实现数据绑定的功能？
然而，我尝试checkout到之后的很多的commit，也还是这样。
请问你当时逐commit查看的时候又遇到这种情况吗？

附上build出来的[vue.js](https://github.com/zhenyong/notebook/files/422163/vue.js.zip)

**Comment by youngwind** [comment]
我用了粗暴的方法：二分排查，发现最早要到这个commit id 4e062e9270c90d6c4e4105bb08f5a1bc61270e2e , 对{{message}}的解析才能正常工作。不过对v-model的解析还没有起作用。

**Comment by zhenyong** [comment]
@youngwind  你应该 checkout 某一个 release 版本，然后再逐条看，你提到的 『30f67ab14090900a28c18db01cf631c037d36e81』 正好处在一个大重构过程，代码确实跑不起来，^_^
