### ISSUE TITLE
observer与emitter如何起作用？

### ISSUE THREAD

**Issue by youngwind** [zhenyong/notebook#3]
我知道：要实现数据绑定，得用到观察者模式。
我在看作者写的[这个commit](https://github.com/vuejs/vue/commit/b5bfc59a704f6d8e01b93352319b356b710ad850)和[这个commit](https://github.com/vuejs/vue/commit/0ad7f54602b41d2dfa82e2368fef1ee2639fecd4)的时候，写了大量observer和emitter的代码。
问题是：我无法理解这两段代码如何起作用的，我也没找到有调用他们的痕迹。

**Comment by zhenyong** [comment]
你试下跑相关的单元测试例子看看有没思绪

**Comment by youngwind** [comment]
@zhenyong 目前我已经搞明白observer的大部分了，谢谢！observer主要是通过Object.defineProperty，监听对象属性的变化，然后触发自定义回调函数，去回调emitter里面的东西。
