### ISSUE TITLE
scope与组件化的关系

### ISSUE THREAD

**Issue by youngwind** [zhenyong/notebook#4]
hi, zhenyong:
请教个问题。我在查看vue的[这个版本](https://github.com/vuejs/vue/tree/e9ecdfe1c0f695396ce790f9637787239d180804)的时候，发现作者写了大量跟scope相关的东西。我不知道这个东西有什么用，我觉得只有涉及到组件化的时候，才有可能谈到实例嵌套，才有可能用到scope来区分各个实例。但是这个版本的vue还没有涉及到组件化呀，所以我就糊涂了。
你对这个有什么看法吗？

> ## (Experimental) New Scope Inheritance Model
> 
> In the previous version, nested Vue instances do not have prototypal inheritance of their data scope. Although you can access parent data properties in templates, you need to explicitly travel up the scope chain with `this.$parent` in JavaScript code or use `this.$get()` to get a property on the scope chain. The expression parser also needs to do a lot of dirty work to determine the correct scope the variables belong to.
> In the new model, we provide a scope inehritance system similar to Angular, in which you can directly access properties that exist on parent scopes. The major difference is that setting a primitive value property on a child scope WILL affect that on the parent scope! This is one of the major gotchas in Angular. If you are somewhat familiar with how prototype inehritance works, you might be surprised how this is possible. Well, the reason is that all data properties in Vue are getter/setters, and invoking a setter will not cause the child scope shadowing parent scopes. See the example [here](http://jsfiddle.net/yyx990803/Px2n6/).
> This is very powerful, but probably should only be available in implicit child instances created by `v-repeat` and `v-if`. Explicit components should retain its own root scope and use some sort of two way binding like `v-with` to sync with outer scope.

引自：项目changes.md文件

**Comment by zhenyong** [comment]
@youngwind
通俗的解释：

把 scope 理解成组件『实例』，组件的信息通过 scope 访问获得，不用太纠结于 "scope" 的命名。

对于 `嵌套关系`，你可以理解成 `原型链`的`继承关系`，当你在 子组件 scope.xx 访问数据时，如果子组件没有 xx，那么就会找到父组件的 scope.xx。

后面新版不用原型链这套，实现起来很复杂不好维护，源码也不太好理解，组件数据传递机制通过 `props` 实现。

**Comment by youngwind** [comment]
@zhenyong 有些明白了，谢谢！
