### ISSUE TITLE
"v-if"的实现疑问

### ISSUE THREAD

**Issue by youngwind** [zhenyong/notebook#5]
hi，zhenyong:
最近我在看早期vue是如何实现v-if的，参考的版本是[这个](https://github.com/vuejs/vue/tree/27874ee31bc3b15a5ef7b0b4ac31899eaeb521d8)。但是我对作者的实现有很多不明白的地方。
考虑如下的情况。

```
<div id="app">
    <p>姓名:{{user.name}}</p>
    <p>年龄:{{user.age}}</p>
    <div v-if="show" id="sub_app">
        <h1>如果show为真,我们就显示{{user.name}}</h1>
    </div>
</div>
```

当DOM遍历解析到v-if的时候，v-if整个的DOM结构会被当成新一个childVue来实例化，也就是说，v-if结构本身是一个实例，这里就变成了实例套实例的情况，父实例是#app，子实例是#sub_app。
面对这种情况，一个关键问题是父实例的数据变化如何传导到子实例。或者说，当改变父实例的user.name时，如何做到子实例中的user.name这个DOM元素也跟着改变。
按照之前实现的逻辑，当某个vue实例的data数据发生变化的时候，就会触发该实例的updateBindingAt方法，然后就会依次找到对应的watcher（后面的省略）。
我观察到vue的实现方式是：在遍历子实例#sub_app的时候，将子实例生成的watcher添加到父实例#app上面去，这样当触发父实例的updateBindingAt的时候，就能找到对应的watcher执行。

然而，我所不理解的是，那么作为一个vue的实例，子实例的_rootBinding，observer这些还有什么作用吗？压根就不需要嘛。因为子实例的数据监听，触发更新DOM，这些都交由父实例来完成了。那么我为什么还需要把v-if当成是实例呢？
还有，如果把v-if当成是实例，那么还存在实例的作用域问题，子实例sub_app是否应该有自己的作用域？如果有，如何构造和维护这个作用域？
我感觉在未来做组件化的时候肯定要处理好作用域的问题，但是，在目前只实现v-if的情况下，有没有更简洁的实现方案？

我这几天看源码看得有些糊涂，还望能够指点一二。

**Comment by zhenyong** [comment]
@youngwind 这两天忙，我中秋再看下，一定回你，互相学习！

**Comment by zhenyong** [comment]
@youngwind 对代码后面的第一段评论: 父组件 a 下嵌套子组件 b 组件

<a
  <b
    {{name}}

框架的设计上，这份 template 中的 name 是属于 a   组件的，参考文档的 slot 分发部分也许能帮助理解

在车上用手机回的，后面我再补充

**Comment by zhenyong** [comment]
@youngwind 

你的问题归纳为：
1. 子实例的事情都由父实例来完成了，为什么还需要把v-if当成是实例呢
2. 父实例的数据变化如何传导到子实例
3. 作用域原理

抱歉没有太多精力仔细看，你说的这个版本也是很早期，我也是回顾了一下，不能保证完全正确：

## 『问题1』v-if

v-if 确实是创建了实例

``` js
this.childVM = this.vm.$addChild({
  el: this.el,
  parent: this.vm,
  _anonymous: true // 先忽略
})
```

这个实例的信息有 dom 元素 `el` 和 父 vm `parent`，
想象一下，v-if 的功能就是动态创建对应部分的节点嘛，
有了 `parent` 就能找到插入位置，有了 `el` 就知道要插入什么。

按照现有的代码来说，我觉得 v-if 这里创建一个子 Vue 实例就是为了使用动画机制，
if.js 中有

``` js
this.childVM.$before(this.ref)
...
this.childVM.$remove()
```

也就是说，v-if 部分的元素出现和删除的时候，是有动画的，
这套动画机制需要这部分元素对应一个 vue 实例，
（我们不讨论为什么需要，目前这个版本就是这么设计的）

这么说！第一个问题是不是解决了呢！^_^

## 『问题2』父组件数据变化如何通知子组件

很抱歉，我脑补不出这个版本的细节，我粗略记得通过 paramAttributes 向子组件传数据。
至于子组件想观察父组件的变化，这个版本我觉得可以
- 直接用 父.$watch
- 父 触发事件，子 监听

## 『问题3』作用域

回到 v-if 的源码，看到 `$addChild`，这个方法也是目前添加子实例的唯一入口

``` js
exports.$addChild = function (opts, BaseCtor) {
  ...
    if (!ChildVue) {
      ChildVue = function (options) {
        ...
      }
      ...
      ChildVue.prototype = this
      ...
  var child = new ChildVue(opts)
  ...
  return child
}
```

就是说父子实例之间就是经典的原型拷贝构造继承？到这里我相信你应该理解了作用域了吧

## 评论

很佩服你的毅力，能逐个 commit 看下去真不容易，因为我已经看到最新的，很多过去版本的细节也不太记得，
当你在思考『为什么它会这样，为什么为什么』的时候，记得告诉自己，『正是因为过去版本的不好，才有后面的版本』

**Comment by youngwind** [comment]
@zhenyong 多谢这么详细的回答，你说的我大概都懂了。我在学习源码的时候确实陷入了你最后提到的思维误区，多谢指出。我已经通过自己的理解用另一种更简单（也更简陋）的方法解决了上述的问题。
