### ISSUE TITLE
Vue什么时候会触发状态机解析path路径？

### ISSUE THREAD

**Issue by youngwind** [zhenyong/notebook#6]
hi, zhenyong：
最近我在看vue状态机解析path路径这一部分，有些问题没有想明白。
[你的理解](https://github.com/zhenyong/notebook/blob/master/vue_notebook/index.md#abf6bda)提到：

> a['b'].c
> 有 [x] 这种的，需要状态机解析 Path.parse("a['b'].c")

然而我在实践中却发现**这种情况依然不会触发状态机解析，而仅仅只会触发expression.js里面的parseExpression函数，而不会触发path.js里面的parsePath函数。**
为什么会出现这种情况呢？

我的demo是这样的：

```
<div id="demo">
    <p>{{user['info'][1].name}}</p>
    <p>{{user.age}}</p>
</div>
```

使用的vue版本是[1.0.26](https://github.com/vuejs/vue/tree/e7932f80eeacf6f7d392bf520e98c4790db9d5c1)

我参考的资料包括：
1. http://jiongks.name/blog/vue-code-review/
2. https://github.com/banama/aboutVue/blob/master/pathStateMachine.md

也提了一个相关的[issue](https://github.com/banama/aboutVue/issues/3)

**Comment by zhenyong** [comment]
@youngwind 过完节回你

**Comment by zhenyong** [comment]
@youngwind 抱歉现在才抽空回复！

根据我的回忆，parsePath 用于解析一个表达式的各层 key 路径，然后对各层对象进行"响应式"属性改造，至于你的实验过程没发现 parsePath 的调用这个问题等同于『为什么初始化阶段（parse directive）不需要解析各层 key 进行响应式改造？』

因为初始化的时候，遍历配置的 data 的各层属性就可以了，没有『根据表达式设置各层 key 响应式』这回事。

**Comment by zhenyong** [comment]
@youngwind 有什么别的解释记得分享
